name: general-tests

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  general-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/esp-8266.git
        lfs: true

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          version:
            - 'VERSION'
          changelog:
            - 'CHANGELOG.md'

    - name: check version and changelog
      if: steps.changes.outputs.version == 'false' || steps.changes.outputs.changelog == 'false'
      run: |
        exit 1

    - name: build
      run: |
        ./local_actions.sh
